services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_LOGIN_API_URL: ${NEXT_PUBLIC_LOGIN_API_URL}
        NEXT_PUBLIC_REGISTER_API_URL: ${NEXT_PUBLIC_REGISTER_API_URL}
        NEXT_PUBLIC_RETRIEVAL_API_URL: ${NEXT_PUBLIC_RETRIEVAL_API_URL}
        NEXT_PUBLIC_UPDATE_FOLDERS_API_URL: ${NEXT_PUBLIC_UPDATE_FOLDERS_API_URL}
        NEXT_PUBLIC_SELECT_DATE_URL: ${NEXT_PUBLIC_SELECT_DATE_URL}
        NEXT_PUBLIC_GET_PPTS_URL: ${NEXT_PUBLIC_GET_PPTS_URL}
        NEXT_PUBLIC_LIST_PDFS_API_URL: ${NEXT_PUBLIC_LIST_PDFS_API_URL}
        NEXT_PUBLIC_DOWNLOAD_PDF_API_URL: ${NEXT_PUBLIC_DOWNLOAD_PDF_API_URL}
        NEXT_PUBLIC_CHAT_API_URL: ${NEXT_PUBLIC_CHAT_API_URL}
    ports:
      - "3000:3000"
